### ISSUE TITLE
Only DH ratchet once in a while?

### ISSUE THREAD

**Issue by S3j5b0** [sebastianv89/double-ratchet#3]
Hi, I have a pretty specific use case where the symmetric ractherts should happen for every message exchange, but DH ratchet should only happen once in a while. Let's say every ten messaegs.

Is there any way to do this in your library, or do you need to do a DH exchange every time?

**Comment by sebastianv89** [comment]
No, I'm sorry. Currently it is hard-coded that a DH exchange is done immediately when possible, so you cannot do that with this library.

Although I don't see too much harm in reducing the frequency of DH ratchets, I'd rather stick to the protocol [as specified](https://signal.org/docs/specifications/doubleratchet/).

**Comment by S3j5b0** [comment]
ah okay, I'm doing an IoT project, where we have som constraints about how oftenthe DH procedure can be made

Thanks a lot for the answer!
